name: Run test cases

on: [push, pull_request]

jobs:

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '27'
        rebar3-version: '3.23.0'
    - run: rebar3 xref
    - run: rebar3 dialyzer
    - run: rebar3 eunit
    - run: rebar3 ct

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        builder:
          - ghcr.io/emqx/emqx-builder/5.4-3:1.17.3-27.2-1
        os:
          - ubuntu24.04
          - ubuntu22.04
          - ubuntu20.04
          - debian12
          - debian11
          - debian10
          - amzn2023
          - el9

    steps:
    - uses: actions/checkout@v4
    - name: Code analyze
      run: |
        version=$(echo ${{ github.ref }} | sed -r  "s .*/.*/(.*) \1 g")
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        docker run --rm -i --name ${{ matrix.os }} -v $(pwd):/repos ${{ matrix.builder }}-${{ matrix.os }} \
          sh -c "cd /repos && make xref && make dialyzer"
    - name: Run tests
      run: |
        version=$(echo ${{ github.ref }} | sed -r  "s .*/.*/(.*) \1 g")
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
        docker run --rm -i --name ${{ matrix.os }} -v $(pwd):/repos ${{ matrix.builder }}-${{ matrix.os }} \
          sh -c "cd /repos && make eunit && make ct"

  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        builder:
          - ghcr.io/emqx/emqx-builder/5.4-3:1.17.3-27.2-1

    steps:
    - uses: actions/checkout@v4
    - name: Code analyze
      run: |
        docker run --rm -i --name alpine -v $(pwd):/repos ${{ matrix.builder }}-alpine3.15.1 \
          sh -c "cd /repos && make xref && make dialyzer"
    - name: Run tests
      run: |
        docker run --rm -i --name alpine -v $(pwd):/repos ${{ matrix.builder }}-alpine3.15.1 \
          sh -c "cd /repos && make eunit && make ct"

